name: get-songs

on:
  schedule:
    - cron: 21 3 * * *

jobs:
  get:
    runs-on: ubuntu-latest

    when:
      if:

    steps:
      - uses: actions/checkout@v3

      - name: cache deno installation and deno.land dependencies
        uses: actions/cache@v2
        with:
          key: deno-${{ hashFiles('/home/runnenr/**/*') }}
          restore-keys: deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.40

      - name: Cache Deno
        run: deno task cache

      - name: Deno info
        run: deno task info

      - name: Get songs
        run: deno task run

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Store gotten songs
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[bot]"
          commit_message: "Got songs ${{ steps.date.outputs.date }}"
