name: get-songs

on:
  workflow_dispatch:
    # for debugging/testing
  schedule:
    - cron: 21 3 * * * # every day at 3:21

jobs:
  get:
    runs-on: ubuntu-latest

    env:
      DENO_DIR: /home/runner/.cache/deno

    steps:
      - uses: actions/checkout@v4

      - name: cache deno installation and deno.land dependencies
        uses: actions/cache@v4
        with:
          key: deno-${{ hashFiles('deno.lock') }}
          restore-keys: deno-
          path: ${{ env.DENO_DIR }}

      - uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: v1.40

      - name: Cache Deno
        run: deno task cache

      - name: Deno info
        run: deno task info

      - name: Get songs
        run: deno task run "yesterday at 12 UTC"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Store gotten songs
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "chore: "
          commit_message: "got yesterday's songs on ${{ steps.date.outputs.date }}"
